### ISSUE TITLE
core.js:12584 ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[SocialServiceConfig]:    StaticInjectorError(Platform: core)[SocialServiceConfig]:

### ISSUE THREAD

**Issue by Sachin124** [JohnnieLi/ng6-social-button#3]
![err](https://user-images.githubusercontent.com/26019527/53326470-b411ce00-390b-11e9-9738-267d8a4197e9.png)

**Comment by JohnnieLi** [comment]
Hi Sachin, as the error described, you need provide the provider in the app.module. like 

providers: [
      ...
      {
          provide: SocialServiceConfig,
          useFactory: getAuthServiceConfigs
      },
  ],
