### ISSUE TITLE
'FacebookLoginProvider[]' is not assignable to parameter 

### ISSUE THREAD

**Issue by AshD91** [JohnnieLi/ng6-social-button#4]
```
import { Ng6SocialButtonModule,SocialServiceConfig, FacebookLoginProvider }from "ng6-social-button";
export function getAuthServiceConfigs() {
    let config = new SocialServiceConfig(
       [ new FacebookLoginProvider("469487816957773")]
    );
    return config;
}
```

It shows  

> error TS2345: Argument of type 'FacebookLoginProvider[]' is not assignable to parameter of type 'SocialServiceConfigItem[]'.
>   Type 'FacebookLoginProvider' is not assignable to type 'SocialServiceConfigItem'.
>     Property 'provider' is missing in type 'FacebookLoginProvider'.

![issue](https://user-images.githubusercontent.com/25473981/59677001-81efe900-91e6-11e9-8789-1dbb65676d62.png)

**Comment by JohnnieLi** [comment]
#3 think it is the same issue with this. we need to config the provider factory in app.module before using facebookProvider or other providers
